In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale, StandardScaler
from sklearn import model_selection
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR


In [4]:
# Uyarı mesajlarının gösterilmemesi için
from warnings import filterwarnings
filterwarnings('ignore')

In [5]:
df = pd.read_csv("Hitters.csv")
df = df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis = 1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.25, random_state=42)


In [10]:
X_train.head()

AtBat   Hits  HmRun  Runs   RBI  Walks  Years  CAtBat   CHits  CHmRun  \
183  328.0   91.0   12.0  51.0  43.0   33.0    2.0   342.0    94.0    12.0   
229  514.0  144.0    0.0  67.0  54.0   79.0    9.0  4739.0  1169.0    13.0   
286  593.0  152.0   23.0  69.0  75.0   53.0    6.0  2765.0   686.0   133.0   
102  233.0   49.0    2.0  41.0  23.0   18.0    8.0  1350.0   336.0     7.0   
153  341.0   95.0    6.0  48.0  42.0   20.0   10.0  2964.0   808.0    81.0   

     CRuns   CRBI  CWalks  PutOuts  Assists  Errors  League_N  Division_W  \
183   51.0   44.0    33.0    145.0     59.0     8.0      True       False   
229  583.0  374.0   528.0    229.0    453.0    15.0      True       False   
286  369.0  384.0   321.0    315.0     10.0     6.0     False        True   
102  166.0  122.0   106.0    102.0    132.0    10.0     False       False   
153  379.0  428.0   221.0    158.0      4.0     5.0      True        True   

     NewLeague_N  
183         True  
229         True  
286        False  
102        False  
153         True

In [12]:
#Model ve tahmin
knn_model=KNeighborsRegressor().fit(X_train,y_train)
knn_model

KNeighborsRegressor()

In [14]:
knn_model.n_neighbors

5

In [16]:
knn_model.metric

'minkowski'

In [20]:
dir(knn_model)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_algorithm_metric',
 '_check_feature_names',
 '_check_n_features',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_fit',
 '_fit_X',
 '_fit_method',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_kneighbors_reduce_func',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_tree',
 '_validate_data',
 '_validate

In [24]:
knn_model.predict(X_test)[0:5]

array([ 510.3334,  808.3334,  772.5   ,  125.5   , 1005.    ])

In [26]:
y_pred=knn_model.predict(X_test)


In [30]:
np.sqrt(mean_squared_error(y_test,y_pred))

426.6570764525201

In [32]:
knn_model

KNeighborsRegressor()

In [48]:
RMSE = []

# İlk k değerini tanımla
k = 0

# KNN modeli için 10 iterasyonluk döngü
for i in range(10):
    k = k + 1
    knn_model = KNeighborsRegressor(n_neighbors=k).fit(X_train, y_train)
    y_pred = knn_model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    RMSE.append(rmse)
    print("k =", k, "için RMSE değeri:", rmse)

k = 1 için RMSE değeri: 455.03925390751965
k = 2 için RMSE değeri: 415.99629571490965
k = 3 için RMSE değeri: 420.6765370082348
k = 4 için RMSE değeri: 428.8564674588792
k = 5 için RMSE değeri: 426.6570764525201
k = 6 için RMSE değeri: 423.5071669008732
k = 7 için RMSE değeri: 414.9361222421057
k = 8 için RMSE değeri: 413.7094731463598
k = 9 için RMSE değeri: 417.84419990871265
k = 10 için RMSE değeri: 421.6252180741266


In [ ]:
#GridSearchCV
#belirlemye çalıştığımız hiperpğarametrelekerin değerlerini belirmelemk için


In [58]:
 knn_params = {"n_neighbors": np.arange(1, 31, 1)}

In [60]:
knn=KNeighborsRegressor()

In [62]:
knn_cv_model = GridSearchCV(knn, knn_params, cv=10)
knn_cv_model.fit(X_train, y_train)


GridSearchCV(cv=10, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])})

In [63]:
best_params = knn_cv_model.best_params_
print("En iyi parametreler:", best_params)

En iyi parametreler: {'n_neighbors': 8}


In [78]:
#final model

# KNN modelini ayarla ve eğit
knn_tuned = KNeighborsRegressor(n_neighbors=knn_cv_model.best_params_["n_neighbors"])
knn_tuned.fit(X_train, y_train)  # Modeli eğit

# Tahmin yap
y_pred = knn_tuned.predict(X_test)

# Hata hesapla
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", rmse)



Root Mean Squared Error: 413.7094731463598


In [86]:
svr_model = SVR(kernel="linear")
svr_model.fit(X_train, y_train)
svr_model

SVR(kernel='linear')

In [88]:
svr_model.predict(X_train)[0:5]

array([219.32624795, 702.43038724, 623.20561122, 153.77539402,
       463.15190748])

In [90]:
svr_model.predict(X_test)[0:5]

array([679.14756648, 633.72885336, 925.68636794, 270.28467553,
       530.26651616])

In [92]:
svr_model.intercept_

array([-80.15195923])

In [94]:
svr_model.coef_

array([[ -1.21839036,   6.0960298 ,  -3.67574544,   0.14217078,
          0.51435925,   1.28388991,  12.55922517,  -0.08693754,
          0.46597181,   2.98259947,   0.5294452 ,  -0.79820801,
         -0.16015542,   0.30872799,   0.28842351,  -1.79560062,
          6.41868986, -10.74313786,   1.33374319]])

In [100]:
#test
y_pred=svr_model.predict(X_test)
np.sqrt(mean_squared_error(y_test,y_pred))

370.04084355099735

In [104]:
# Hiperparametreleri tanımla
svr_params = {
    "C": [0.1, 1, 10, 100]
}

# GridSearchCV modelini tanımla ve eğit
svr_cv_model = GridSearchCV(svr_model, svr_params, cv=5)
svr_cv_model.fit(X_train, y_train)


GridSearchCV(cv=5, estimator=SVR(kernel='linear'),
             param_grid={'C': [0.1, 1, 10, 100]})

In [105]:
svr_cv_model.best_params_

{'C': 10}

In [ ]:
#Yapay sinir ağları

In [ ]:
scaler=StandardScaler()

In [121]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# MLP modelini ayarla ve eğit
mlp_model = MLPRegressor().fit(X_train_scaled, y_train)

y_pred = mlp_model.predict(X_test_scaled)

# Hata hesapla
rmse = np.sqrt(mean_squared_error(y_test, y_pred))                  

In [115]:
mlp_model.predict(X_test_scaled)[0:5]

array([25.15789903, 43.45855743, 78.78150679, 12.16354059, 22.59262315])

In [ ]:
#Model tuning

In [ ]:
#CART